// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Pastebin struct {
	UserUuid  uuid.UUID          `json:"user_uuid"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Title     string             `json:"title"`
	Content   string             `json:"content"`
	UrlUuid   uuid.UUID          `json:"url_uuid"`
	Extension string             `json:"extension"`
}

type Token struct {
	ID             int32              `json:"id"`
	Token          string             `json:"token"`
	UserUuid       pgtype.UUID        `json:"user_uuid"`
	RefreshToken   string             `json:"refresh_token"`
	NewAccessToken string             `json:"new_access_token"`
	IsValid        *bool              `json:"is_valid"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Url struct {
	UrlUuid uuid.UUID   `json:"url_uuid"`
	UrlName interface{} `json:"url_name"`
}

type User struct {
	Uuid      uuid.UUID          `json:"uuid"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	AuthType  string             `json:"auth_type"`
	OauthID   string             `json:"oauth_id"`
}
